# Generated by Django 5.0.14 on 2025-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clickestudosAPP",
            "0002_remove_postagem_categoria_material_delete_categoria_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("professor", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("nota", models.IntegerField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
